### ISSUE TITLE
ImportError: cannot import name etree

### ISSUE THREAD

**Issue by T28PJ** [fetzerch/fritzcollectd#13]
Hi,

I get the following message in journalctl when starting collectd:

```
Mar 24 02:48:26 raspberrypi collectd[26698]: python plugin: Error importing module "fritzcollectd".
Mar 24 02:48:26 raspberrypi collectd[26698]: Unhandled python exception in importing module: ImportError: cannot import name etree
```

raspbian with lxml-4.2.1 installed via pip3

Please advise

**Comment by fetzerch** [comment]
Collectd uses Python 2.7 so you'd need to install the dependencies via `pip2`.

```console
pi@raspberrypi:~ $ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 9.3 (stretch)
Release:        9.3
Codename:       stretch
pi@raspberrypi:~ $ apt-cache depends collectd | grep python
  Recommends: libpython2.7
```

**Comment by T28PJ** [comment]
Thank you very much. That basically worked. But now collectd is sending me this message via `systemctl status`

```
Mar 24 18:54:15 raspberrypi collectd[2681]: read-function of plugin `python.fritzcollectd' failed. Will suspend it for 40.000 seconds.
Mar 24 18:54:55 raspberrypi collectd[2681]: Unhandled python exception in read callback: ServiceError: Unknown Service: LANEthernetInterfaceConfig:1
Mar 24 18:54:55 raspberrypi collectd[2681]: Traceback (most recent call last):
Mar 24 18:54:55 raspberrypi collectd[2681]:   File "/usr/local/lib/python2.7/dist-packages/fritzcollectd.py", line 263, in callback_read
                                                config.read()
Mar 24 18:54:55 raspberrypi collectd[2681]:   File "/usr/local/lib/python2.7/dist-packages/fritzcollectd.py", line 166, in read
                                                values = self._read_data(self.SERVICE_ACTIONS_AUTH, self._fc_auth)
Mar 24 18:54:55 raspberrypi collectd[2681]:   File "/usr/local/lib/python2.7/dist-packages/fritzcollectd.py", line 199, in _read_data
                                                **parameters)
Mar 24 18:54:55 raspberrypi collectd[2681]:   File "/usr/local/lib/python2.7/dist-packages/fritzconnection/fritzconnection.py", line 405, in call_action
                                                action = self._get_action(service_name, action_name)
Mar 24 18:54:55 raspberrypi collectd[2681]:   File "/usr/local/lib/python2.7/dist-packages/fritzconnection/fritzconnection.py", line 378, in _get_action
                                                raise ServiceError('Unknown Service: ' + service_name)
Mar 24 18:54:55 raspberrypi collectd[2681]: ServiceError: Unknown Service: LANEthernetInterfaceConfig:1
Mar 24 18:54:55 raspberrypi collectd[2681]: read-function of plugin `python.fritzcollectd' failed. Will suspend it for
```

What did I miss?

**Comment by fetzerch** [comment]
Can you please run `fritzstatus` and ` fritzconnection --services --password <PASSWORD>` and post the output? I assume your box seems to not support `LANEthernetInterfaceConfig:1` and I'll have to make reading from that service conditionally.

**Comment by T28PJ** [comment]
Sure.

```
pi@raspberrypi:~ $ fritzstatus

FritzStatus:
version:            0.5.1
model:              FRITZ!Box 3490
is linked:          True
is connected:       True
external ip:        1.1.1.1
uptime:             15:25:02
bytes send:         1021240632
bytes received:     4686090421
max. bit rate:      ('47.7 MBit/s', '95.4 MBit/s')
pi@raspberrypi:~ $ fritzconnection --services --password XXX

FritzConnection:
version:            0.6
model:              FRITZ!Box 3490
Servicenames:
                    Any:1
                    WANCommonInterfaceConfig:1
                    WANDSLLinkConfig:1
                    WANIPConnection:1
                    WANIPv6FirewallControl:1
()
```

**Comment by fetzerch** [comment]
I hope I'll find time to look into this soon. In the meantime it should work for you if you just remove the `Password` line from fritzcollectd's config. Then it won't try to read the problematic ethernet stats field.

**Comment by fetzerch** [comment]
Fixed in https://github.com/fetzerch/fritzcollectd/commit/7dc71018d51d202c6df6f427f9bf6476023d09d3 in `fritzcollectd-0.6.0`.
