### ISSUE TITLE
Possible support for Fritz!OS 6.98 and newer

### ISSUE THREAD

**Issue by hbokh** [fetzerch/fritzcollectd#20]
Moved from #15. 

`fritzcollectd` stopped working when heading towards the FritzOS v7 release.
From the logs:

```
Sep 27 12:46:24 bsd002 collectd[71071]: fritzcollectd: Invalid data received, attempting to reconnect
Sep 27 12:46:25 bsd002 collectd[71071]: Unhandled python exception in read callback: XMLSyntaxError: Opening and ending tag mismatch: HR line 1 and BODY, line 1, column 174 (line 1)
Sep 27 12:46:25 bsd002 collectd[71071]: read-function of plugin `python.fritzcollectd' failed. Will suspend it for 20.000 seconds.
```

This was self-inflicted since I upgraded to `FRITZ!OS: 06.98-61351 BETA` and `FRITZ!OS: 06.98-61788 BETA`, but I think issues coming from the new OS-version will reappear sooner or later.

It seems there are some **differences** in the Services/Actions/Arguments.
For instance have a look at `(ServiceAction('WANCommonInterfaceConfig:1', 'GetAddonInfos')`: the `GetAddonInfos` has been dropped and the bytes / packets sent & received is different (can be found in Johannes' output https://github.com/fetzerch/fritzcollectd/issues/15#issuecomment-402272354):

```
Servicename:        WANCommonInterfaceConfig:1
Actionname:         GetCommonLinkProperties
                        ('NewLayer1DownstreamMaxBitRate', 'out', 'ui4')
                        ('NewLayer1UpstreamMaxBitRate', 'out', 'ui4')
                        ('NewPhysicalLinkStatus', 'out', 'string')
                        ('NewWANAccessType', 'out', 'string')
Actionname:         GetTotalBytesReceived
                        ('NewTotalBytesReceived', 'out', 'ui4')
Actionname:         GetTotalBytesSent
                        ('NewTotalBytesSent', 'out', 'ui4')
Actionname:         GetTotalPacketsReceived
                        ('NewTotalPacketsReceived', 'out', 'ui4')
Actionname:         GetTotalPacketsSent
                        ('NewTotalPacketsSent', 'out', 'ui4')
Actionname:         X_AVM-DE_GetOnlineMonitor
--- cut --- 8< ---
```

Also shown on pages 14 / 15 of [AVM TR-064 first_steps](https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/AVM_TR-064_first_steps.pdf). 

FYI `fritzstatus` is still working but is using different actions:

```
# fritzstatus

FritzStatus:
version:            0.5.1
model:              FRITZ!Box 7581
is linked:          True
is connected:       True
external ip:        a.b.c.d
uptime:             00:18:02
bytes send:         5866475
bytes received:     34814331
max. bit rate:      ('4.5 MBit/s', '29.0 MBit/s')
```

For now I have disabled `fritzcollectd`.

**Comment by hbokh** [comment]
Might come in handy (enabled `LogTraces true`):

```
Sep 29 15:04:59 bsd002 collectd[73970]: Unhandled python exception in init callback: XMLSyntaxError: Opening and ending tag mismatch: HR line 1 and BODY, line 1, column 174 (line 1)
Sep 29 15:04:59 bsd002 collectd[73970]: Traceback (most recent call last):
Sep 29 15:04:59 bsd002 collectd[73970]:   File "/usr/local/lib/python2.7/site-packages/fritzcollectd/__init__.py", line 294, in callback_init     config.init()
Sep 29 15:04:59 bsd002 collectd[73970]:   File "/usr/local/lib/python2.7/site-packages/fritzcollectd/__init__.py", line 152, in init     if not self._fc.call_action('WANIPConnection:1', 'GetStatusInfo'):
Sep 29 15:04:59 bsd002 collectd[73970]:   File "/usr/local/lib/python2.7/site-packages/fritzconnection/fritzconnection.py", line 406, in call_action     return action.execute(**kwargs)
Sep 29 15:04:59 bsd002 collectd[73970]:   File "/usr/local/lib/python2.7/site-packages/fritzconnection/fritzconnection.py", line 130, in execute     result = self.parse_response(response.content)
Sep 29 15:04:59 bsd002 collectd[73970]:   File "/usr/local/lib/python2.7/site-packages/fritzconnection/fritzconnection.py", line 142, in parse_response     root = etree.fromstring(response)
Sep 29 15:04:59 bsd002 collectd[73970]:   File "src/lxml/etree.pyx", line 3213, in lxml.etree.fromstring
Sep 29 15:04:59 bsd002 collectd[73970]:   File "src/lxml/parser.pxi", line 1877, in lxml.etree._parseMemoryDocument
Sep 29 15:04:59 bsd002 collectd[73970]:   File "src/lxml/parser.pxi", line 1765, in lxml.etree._parseDoc
Sep 29 15:04:59 bsd002 collectd[73970]:   File "src/lxml/parser.pxi", line 1127, in lxml.etree._BaseParser._parseDoc
Sep 29 15:04:59 bsd002 collectd[73970]:   File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
Sep 29 15:04:59 bsd002 collectd[73970]:   File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
Sep 29 15:04:59 bsd002 collectd[73970]:   File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
Sep 29 15:04:59 bsd002 collectd[73970]: XMLSyntaxError: Opening and ending tag mismatch: HR line 1 and BODY, line 1, column 174 (line 1)
Sep 29 15:04:59 bsd002 collectd[73970]: fritzcollectd: Invalid data received, attempting to reconnect
Sep 29 15:04:59 bsd002 collectd[73970]: Unhandled python exception in read callback: XMLSyntaxError: Opening and ending tag mismatch: HR line 1 and BODY, line 1, column 174 (line 1)
Sep 29 15:04:59 bsd002 collectd[73970]: Traceback (most recent call last):
Sep 29 15:04:59 bsd002 collectd[73970]:   File "/usr/local/lib/python2.7/site-packages/fritzcollectd/__init__.py", line 305, in callback_read     config.init()
Sep 29 15:04:59 bsd002 collectd[73970]:   File "/usr/local/lib/python2.7/site-packages/fritzcollectd/__init__.py", line 152, in init     if not self._fc.call_action('WANIPConnection:1', 'GetStatusInfo'):
Sep 29 15:04:59 bsd002 collectd[73970]:   File "/usr/local/lib/python2.7/site-packages/fritzconnection/fritzconnection.py", line 406, in call_action     return action.execute(**kwargs)
Sep 29 15:04:59 bsd002 collectd[73970]:   File "/usr/local/lib/python2.7/site-packages/fritzconnection/fritzconnection.py", line 130, in execute     result = self.parse_response(response.content)
Sep 29 15:04:59 bsd002 collectd[73970]:   File "/usr/local/lib/python2.7/site-packages/fritzconnection/fritzconnection.py", line 142, in parse_response     root = etree.fromstring(response)
Sep 29 15:04:59 bsd002 collectd[73970]:   File "src/lxml/etree.pyx", line 3213, in lxml.etree.fromstring
Sep 29 15:04:59 bsd002 collectd[73970]:   File "src/lxml/parser.pxi", line 1877, in lxml.etree._parseMemoryDocument
Sep 29 15:04:59 bsd002 collectd[73970]:   File "src/lxml/parser.pxi", line 1765, in lxml.etree._parseDoc
Sep 29 15:04:59 bsd002 collectd[73970]:   File "src/lxml/parser.pxi", line 1127, in lxml.etree._BaseParser._parseDoc
Sep 29 15:04:59 bsd002 collectd[73970]:   File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
Sep 29 15:04:59 bsd002 collectd[73970]:   File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
Sep 29 15:04:59 bsd002 collectd[73970]:   File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
Sep 29 15:04:59 bsd002 collectd[73970]: XMLSyntaxError: Opening and ending tag mismatch: HR line 1 and BODY, line 1, column 174 (line 1)
Sep 29 15:04:59 bsd002 collectd[73970]: read-function of plugin `python.fritzcollectd' failed. Will suspend it for 20.000 seconds.
```

**Comment by hbokh** [comment]
I happened to get it working again without altering any services or actions etc. as mentioned above.
Using `truss` ("strace" on FreeBSD) against collectd. `http://fritzbox:49000/igddesc.xm` gave an `ERR_INVALID_REQ`.

So I changed `Address` from "fritzbox" to the IP address (used to work before...).

Only thing missing now is the uptime / DSL active in Grafana.

**Comment by fetzerch** [comment]
I tried to reproduce the issue, but I'm not able to. For me hostname, ip and `fritz.box` work (on a Fritzbox 7490 with OS 7.01). `GetAddonInfos` is documented in https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/IGD2.pdf.

It would be possible to use `GetTotalBytesReceived`/`GetTotalBytesSent` instead of `GetAddonInfos` but there don't seem to be alternatives for `NewByteReceiveRate`/`NewByteSentRate`.

In general the API is quite fragile, for example if you connect with password, some actions behave differently. See https://github.com/fetzerch/fritzcollectd/commit/9e346d05909bd405650c46ea1b03df990514b727.
