### ISSUE TITLE
Unknown Service: WANIPConnection:1

### ISSUE THREAD

**Issue by upD8R** [fetzerch/fritzcollectd#31]
HI there,

fist time setting up collectd and all the other tools but I fail here:
```
Aug 20 22:37:53 raspberrypi collectd[1996]: Unhandled python exception in init callback: ServiceError: Unknown Service: WANIPConnection:1
Aug 20 22:37:53 raspberrypi collectd[1996]: Initialization complete, entering read-loop.
Aug 20 22:37:53 raspberrypi collectd[1996]: fritzcollectd: Calling action: WANIPConnection:1 GetStatusInfo {}
Aug 20 22:37:53 raspberrypi collectd[1996]: Unhandled python exception in read callback: ServiceError: Unknown Service: WANIPConnection:1
Aug 20 22:37:53 raspberrypi collectd[1996]: read-function of plugin `python.fritzcollectd' failed. Will suspend it for 20.000 seconds.
```

Any ideas? If I disable username/password I don't get any obvious error message but I also don't see any data in Grafana. Not sure how to check if something is inserted into the DB.`

**Comment by upD8R** [comment]
After some further digging it seems the error already happens with fritzconnection, e.g. fritzstatus shows the following:
```
FritzStatus:
version:            0.7.1
Traceback (most recent call last):
  File "/usr/local/bin/fritzstatus", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/fritzconnection/fritzstatus.py", line 239, in main
    _print_status(_get_cli_arguments())
  File "/usr/local/lib/python2.7/dist-packages/fritzconnection/fritzstatus.py", line 235, in _print_status
    password=arguments.password,
  File "/usr/local/lib/python2.7/dist-packages/fritzconnection/fritzstatus.py", line 190, in print_status
    fs = FritzStatus(address=address, port=port, user=user, password=password)
  File "/usr/local/lib/python2.7/dist-packages/fritzconnection/fritzstatus.py", line 60, in __init__
    self.last_bytes_sent = self.bytes_sent
  File "/usr/local/lib/python2.7/dist-packages/fritzconnection/fritzstatus.py", line 111, in bytes_sent
    'GetTotalBytesSent')
  File "/usr/local/lib/python2.7/dist-packages/fritzconnection/fritzconnection.py", line 442, in call_action
    action = self._get_action(service_name, action_name)
  File "/usr/local/lib/python2.7/dist-packages/fritzconnection/fritzconnection.py", line 415, in _get_action
    raise ServiceError('Unknown Service: ' + service_name)
fritzconnection.fritzconnection.ServiceError: Unknown Service: WANCommonInterfaceConfig:1
```

**Comment by upD8R** [comment]
Fallback to fritzconnection 0.7.3 seems to solve my problem but in general it would be good to understand what's going wrong here ..,

**Comment by fetzerch** [comment]
Thanks for the report and for starting the discussion in https://bitbucket.org/kbr/fritzconnection/issues/37/unknown-service-wancommoninterfaceconfig-1.
For the time being I've updated the package (v0.6.3) to require fritzconnection<0.8.0. I need to find time to look into the fritzconnection change and see how fritzcollectd has to be adapted.
